language: ruby

cache: bundler

rvm:
- "2.3"
- "2.4"
- "2.5"
- "2.6"
- "2.7"

addons:
  apt:
    packages:
    - graphviz

before_install:
- gem install bundler

before_script:
- gem uninstall sassc
- gem install sassc -- --disable-march-tune-native

script:
- bundle exec rspec
