language: ruby

cache: bundler

rvm:
  - "2.3.0"
  - "2.4.0"
  - "2.5.0"
  - "2.6.0"

addons:
  apt:
    packages:
    - graphviz

before_install:
- gem install bundler

script:
- bundle exec rspec
