require 'singleton'

require 'slim'
require 'rdiscount'
require 'coderay'
require 'yaml'
require 'sass'
require 'sinatra/base'
require "sinatra/reloader"
require 'sass/plugin/rack'
require 'docopt'
require 'colsole'

require 'madness/version'
require 'madness/settings'
require 'madness/server_helper'
require 'madness/server_base'
require 'madness/server'
require 'madness/document'
require 'madness/navigation'
require 'madness/breadcrumbs'
require 'madness/command_line'
